### ISSUE TITLE
push ucscsession to pip?

### ISSUE THREAD

**Issue by jayhesselberth** [daler/ucscsession#1]
Ryan –

Can you push the github version to pip? The version on pip has `requests.Session()` errors like:

```
jayhesselberth@urburger ~/devel/ucsc_snapshots/ucsc_snapshots
$ python ucsc_snapshots.py test.bed 418769025_5AGiEoDDyzG68OxY9OK7QV0LRHKX
DEBUG:ucscsession.session(hgsid):hgsid=418769025_5AGiEoDDyzG68OxY9OK7QV0LRHKX
Traceback (most recent call last):
  File "ucsc_snapshots.py", line 339, in <module>
    sys.exit(main())
  File "ucsc_snapshots.py", line 336, in main
    return ucsc_snapshots(bedfilename, sessionid, **kwargs)
  File "ucsc_snapshots.py", line 52, in ucsc_snapshots
    session = Session(rev_display, no_delay, verbose)
  File "ucsc_snapshots.py", line 75, in __init__
    ucscsession.session._UCSCSession.__init__(self)
  File "/usr/local/lib/python2.7/site-packages/ucscsession/session.py", line 47, in __init__
    self.cart = self.cart_info()
  File "/usr/local/lib/python2.7/site-packages/ucscsession/session.py", line 142, in cart_info
    response = self.session.get(self.cart_url)
  File "/usr/local/lib/python2.7/site-packages/ucscsession/session.py", line 77, in session
    self._session = requests.session(params=dict(hgsid=self.hgsid))
TypeError: session() takes no arguments (1 given)
```

**Comment by daler** [comment]
Sorry about that, I just uploaded v0.1.1 to PyPI, so you should be able to `pip install --upgrade ucscsession` to get the new version. Thanks for the reminder.
